name: user-management
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        MONGODB_URI: ${{ secrets.MONGODB_URI}}
        NODE_ENV: ${{ secrets.NODE_ENV }}

    - name: Install dependencies
      run: npm install

    - name: Creating env file
      run: |
        touch .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI}} >> .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
          echo SECRET=${{ secrets.SECRET }} >> .env
          cat .env

    - name: Checking lint
      run: npm run lint

    - name: Running tests
      timeout-minutes: 5  # Definindo um limite de tempo de 5 minutos
      run: |
        npm run test
        echo "Testes finalizados em $(date)"

    - name: Start application
      run: npm start &

    - name: Wait for application to start
      run: sleep 10s

    - name: Test health-check endpoint
      run: curl http://localhost:3333/api/health-check

    - name: Check for errors
      if: ${{ job.status != 'success' }}
      run: exit 1

    - name: Merge to main
      if: ${{ job.status == 'success' }}
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: main
        github_token: ${{ secrets.ACCESS_TOKEN }}
