name: CI/CD flow config
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start &

    - name: Wait for application to start
      run: sleep 10s

    - name: Test health-check endpoint
      run: curl http://localhost:3000/health-check

  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #   - name: start app and test
  #     run:
  #       bash -c "npm && npm install
  #       && npm run eslint
  #       && npm run start & sleep 15
  #       && curl http://localhost:4040/api/health-check"



  # Pipeline-4uth:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3

  #     - name: running eslint
  #       run: npm run lint

  #     - run: echo "This job's status is ${{ job.status }}."
