name: CI/CD flow config
on: [push]
jobs:
  Pipeline-4uth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: installing node_modules
        run: npm install
      # - name: building project
      #   run: npm run build
      # - name: running prettier
      #   run: npm run prettier

      # - name: running eslint
      #   run: npm run lint

      # - name: health-check test
      #   run: npm run test:fn

      - run: echo "This job's status is ${{ job.status }}."
