name: CI/CD flow config
on: [push]
jobs:
  Pipeline-4uth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: installing node_modules
        run: npm install

      - name: running eslint
        run: npm run lint

      - run: echo "This job's status is ${{ job.status }}."
